### ISSUE TITLE
Warning message: deprecated function

### ISSUE THREAD

**Issue by rdecook16** [brad-cannell/codebookr#47]
In running the codebook() function on a labelled data.frame, I received this error message:

Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
i Please use `reframe()` instead.
i When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped data frame and adjust accordingly.
i The deprecated feature was likely used in the codebookr package.
  Please report the issue at <https://github.com/brad-cannell/codebookr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

It's only a warning, but a little disconcerting.  The codebook is generated as a Word Doc and seems fine.

**Comment by mbcann01** [comment]
Hi @rdecook16 ,

Thank you for letting me know! This should be a relatively easy fix... if I can find the time to fix it! 

Thanks again!
Brad

**Comment by mbcann01** [comment]
This is fixed in #45
