### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by danfreak** [brad-cannell/codebookr#48]
I get the following error:
Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
always returns an ungrouped data frame and adjust accordingly.
 ℹ The deprecated feature was likely used in the codebookr package.
   Please report the issue at
   <https://github.com/brad-cannell/codebookr/issues>.
This warning is displayed once every 8 hours.
 Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
 generated.

**Comment by mbcann01** [comment]
Thank you, @danfreak ! I'll get this cleaned up as soon as I can.

**Comment by mbcann01** [comment]
This is fixed in #45. I'll push to CRAN soon.
