### ISSUE TITLE
Codebookr - L2C Master Log

### ISSUE THREAD

**Issue by areddy647712** [brad-cannell/codebookr#9]
Hi Brad,

This is the error I received when passing the Master Log data frame to the codebook function. 

> Error in `dplyr::mutate()`:
> ! Problem while computing `Value = date`.
> ✖ `Value` must be a vector, not a function.

These are the steps I took:

1. Load Master_Log _version2_
2. glimpse(Master_Log _version2_)
3. Pass the data frame to the codebook function

I hope this was helpful. I also tried to use the cb_add_col_attributes() function and assign attributes to columns with dates in them.

Thank you!
Aish

**Comment by mbcann01** [comment]
Thank you!

**Comment by mbcann01** [comment]
# POSIXct issue

It looks like this error is caused by POSIXct columns. I'm not sure why yet. It also looks like the code that is struggling is on lines 72-76 of `cb_summary_stats_time.R`

- [ ] Update the study data to include a POSIXct column
